### ISSUE TITLE
Support handlebars template for default style project

### ISSUE THREAD

**Issue by lettenj61** [lettenj61/rig#26]

**Comment by lettenj61** [comment]
I think I cleared out what I want to do.
First, there are few deviations between my template impls and original giter8 template. When we accept Handlebars, there will be 3 syntax to write trmplate, and I don't want that to happen.

So these are the things I should do:
- rewrite current template to stick to giter8 one
- bring handlebars in and make simple projects use it by default

**Comment by lettenj61** [comment]
made a branch for this, need more tests

**Comment by lettenj61** [comment]
##### Imagine parameters in toml format

```toml
[params]
name = "Your name here"
version = "0.1.0"

# using indexer API
[params."serde_version"]
default = "0.9"
index = { host = "cratesio" }

# using validators
[params.authors]
default = "example@nosuch.domain.brahbrah"
validation = ["email"]
```
